node_name                'euonymus'
client_key               '/Users/euonymus/Sites/belongsto/digital_ocean2/chef/.chef/euonymus.pem'
validation_client_name   'chef-validator'
validation_key           '/etc/chef-server/chef-validator.pem'
chef_server_url          'https://euonymus-no-MacBook-Pro.local/organizations/myorg'
syntax_check_cache_path  '/Users/euonymus/Sites/belongsto/digital_ocean2/chef/.chef/syntax_check_cache'
